# Azure DevOps pipeline example integrating Key Vault
trigger:
  branches:
    include:
      - main

variables:
  - group: KeyVault-Secrets # Securely linked variable group

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - checkout: self
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: "svc-connection-rg-only"
              KeyVaultName: "prod-keyvault"
              SecretsFilter: "*"
              RunAsPreJob: true
          - script: |
              echo "Using secret in pipeline runtime..."
              # Safely reference secret without printing its value
              if [ -n "$DB_PASSWORD" ]; then
                echo "Secret retrieved successfully."
              else
                echo "Secret not found."
              fi
            displayName: "Consume Secrets"
