# Azure DevOps Pipeline - Secure Telemetry Deployment
# Demonstrates fetching secrets from Azure Key Vault at runtime

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: telemetry-secrets # Variable group linked to Key Vault

steps:
  - task: AzureCLI@2
    displayName: "Terraform Init & Apply"
    inputs:
      azureSubscription: "Telemetry-Service-Connection"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        echo "Running Terraform to provision secure telemetry pipeline"
        cd terraform
        terraform init
        terraform apply -auto-approve

  - task: AzureKeyVault@2
    displayName: "Fetch secrets from Key Vault"
    inputs:
      azureSubscription: "Telemetry-Service-Connection"
      KeyVaultName: "race-telemetry-kv"
      SecretsFilter: "sql-admin-password,cosmos-primary-key"
      RunAsPreJob: false

  - script: |
      echo "Retrieved SQL password: $(sql-admin-password)"
      echo "Retrieved Cosmos Key (masked): $(cosmos-primary-key)"
    displayName: "Verify secrets pulled securely"
