# GitHub Actions Workflow - Secure Telemetry Deployment
# Demonstrates pulling secrets securely from Azure Key Vault

name: Secure Telemetry Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      - name: Retrieve Key Vault Secrets
        run: |
          echo "Fetching secrets from Key Vault..."
          SQL_PASSWORD=$(az keyvault secret show \
            --name sql-admin-password \
            --vault-name race-telemetry-kv \
            --query value -o tsv)
          COSMOS_KEY=$(az keyvault secret show \
            --name cosmos-primary-key \
            --vault-name race-telemetry-kv \
            --query value -o tsv)

          echo "SQL_PASSWORD=$SQL_PASSWORD" >> $GITHUB_ENV
          echo "COSMOS_KEY=$COSMOS_KEY" >> $GITHUB_ENV

      - name: Deploy Application with Secrets
        run: |
          echo "Deploying telemetry system with secure secrets..."
          echo "SQL Password: $SQL_PASSWORD"
          echo "Cosmos Key (masked): $COSMOS_KEY"
